name: Update Boston Black Events

on:
  schedule:
    # Run daily at 2:00 AM
    - cron: '0 2 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run scraper
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          MEETUP_TOKEN: ${{ secrets.MEETUP_TOKEN }}
        run: python event_scraper.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          timestamp=$(date -u)
          git commit -m "Update events data: ${timestamp}" || exit 0
          git push